#!/bin/bash
-rwxr--r-- 1 root root 16 Mar 15 03:06 0-current_working_directory
-rw-r--r-- 1 root root 13 Mar  8 14:22 10-back
-rwxr--r-- 1 root root 13 Mar  8 14:52 12-file_type
-rwxr--r-- 1 root root 13 Mar  8 15:06 13-symbolic_link
-rw-r--r-- 1 root root 13 Mar  8 15:13 14-copy_html
-rw-r--r-- 1 root root 59 Mar 15 04:08 1-listit
-rw-r--r-- 1 root root 17 Mar 15 04:30 2-bring_me_home
-rw-r--r-- 1 root root 13 Mar  8 13:13 3-listfiles
-rw-r--r-- 1 root root 13 Mar  8 13:28 4-listmorefiles
-rw-r--r-- 1 root root 13 Mar  8 13:35 5-listfilesdigitonly
-rw-r--r-- 1 root root 13 Mar  8 13:53 6-firstdirectory
-rw-r--r-- 1 root root 13 Mar  8 14:01 7-movethatfile
-rw-r--r-- 1 root root 13 Mar  8 14:09 8-firstdelete
-rw-r--r-- 1 root root 13 Mar  8 14:17 9-firstdirdeletion
drwxr-xr-x 2 root root 22 Mar  8 14:33 boot
lrwxrwxrwx 1 root root  6 Mar 15 02:55 __ls__ -> __ls__
-rw-r--r-- 1 root root  6 Mar  8 14:23 README.md
